load("//tools/nugget:defs.bzl", "cc_nugget_library")

cc_nugget_library(
    name = "animal",
    nuggets = ["animal.nugget"],
    nugget_deps = [
        "//fish:fish",
    ],
    visibility = ["//visibility:public"]
)
